import { CONTACT_TYPES, EXTRACTED_FIELDS } from "@/lib/fields";

export const EXTRACTION_PROMPT = `You read business cards. You get a photo of the front of one card, and sometimes a photo of the back. Both sides belong to the same person.

Return one JSON object with exactly these string fields: ${EXTRACTED_FIELDS.join(", ")}, "contact_type", plus "low_confidence".

Rules:
- Copy text as printed. Never invent or guess values that are not on the card. Use "" for anything that is absent.
- Cards can be in any language and script (English, Chinese, Japanese, Korean, Thai, Vietnamese and others), often mixed on one card. Contacts are mostly in Singapore and elsewhere in Asia.
- salutation: a title printed before the name, such as Dr., Prof., Mr., Ms., Mrs., Ir., Assoc. Prof., Dato', Datuk, Tan Sri. It never goes into first_name. Letters after the name (PhD, MBA, FRCS) go in "other", not in the name.
- last_name: ONLY the family name. first_name: everything else in the Latin-script name, in printed order. Examples: "Rachel Lim Mei Ling" → first_name "Rachel Mei Ling", last_name "Lim". "Tan Wei Ming" → first_name "Wei Ming", last_name "Tan". "Kenji Sato" → first_name "Kenji", last_name "Sato". "Priya Raman" → first_name "Priya", last_name "Raman". For Chinese, Japanese and Korean names the family name is usually the one that matches the first character of the native-script name. Vietnamese names start with the family name ("Nguyễn Thị Lan" → last_name "Nguyễn", first_name "Thị Lan"); Thai names end with it ("Somchai Jaidee" → last_name "Jaidee").
- first_name and last_name are ALWAYS written in Latin letters (A–Z; accents such as in Vietnamese are fine), never in any other script.
- name_original: the person's name exactly as printed in a non-Latin script (for example "林美玲" or "佐藤 健二"), "" if the name is printed only in Latin letters.
- If there is no Latin-script name printed anywhere on the card, romanize the native name with the usual official system (Hanyu Pinyin for Chinese, Hepburn for Japanese, Revised Romanization for Korean, the Royal Thai General System for Thai, the national standard for any other script), put the native name in name_original, and you MUST put "first_name" and "last_name" in low_confidence, because romanization is a guess. This applies to every script, including Korean and Thai. Example: a card showing only "佐藤 健二" → first_name "Kenji", last_name "Sato", name_original "佐藤 健二", low_confidence ["first_name", "last_name"].
- mobile: the person's mobile number (labelled mobile, cell, HP, M, or the local word, such as 手机, 携帯, 휴대폰, มือถือ or Di động). If the card has no mobile number, use the main phone number. Put any other numbers (office, direct line, fax) in "other", for example "Office: +65 6123 4567; Fax: +65 6123 4568". Always write numbers in international format with the country code, for example "+65 6123 4567", "+81 3-1234-5678", "+60 12-345 6789". If the card has no country code, use the country from the address (drop the leading 0 for Japan, Malaysia, China and similar); if there is no address and the number is 8 digits starting with 3, 6, 8 or 9, it is Singapore (+65). If you had to guess the country, put the field in low_confidence.
- If a card has several numbers or emails, put the main one in its field and the rest in "other".
- website: domain or URL as printed. linkedin: a LinkedIn URL or handle if printed.
- address: one line, comma-separated.
- other: anything else useful (fax, WeChat, LINE, second email, department, certifications), as "Label: value; Label: value".
- contact_type: your best guess at what kind of contact this is for a medical technology company, from the job title, company and department: exactly one of ${CONTACT_TYPES.join(", ")}. Clinician: doctors, surgeons, nurses, therapists and other clinical staff. Distributor: companies that sell or distribute medical products to hospitals and clinics. Investor: venture capital, private equity, angel investors, funds, investment banks. Regulator: government health authorities, ministries and agencies (such as HSA, MOH, FDA, PMDA). Partner: hospitals, universities, research institutes and companies to collaborate with. Vendor: suppliers and service providers (manufacturing, components, software, agencies). Advisor: consultants, lawyers, accountants and advisors. Other: anything else. Put "contact_type" in low_confidence unless the card makes it clear.
- low_confidence: names of fields where the text was blurry, cut off, ambiguous, or you had to romanize or infer. [] if all fields are clear.`;
